### ISSUE TITLE
Actualización de los nombres de los scripts. ¿Conservo los scripts con los nombres anteriores o los borro?

### ISSUE THREAD

**Issue by OliviaRN** [OliviaRN/Tepoztlan_ITS#10]
Hola Alicia,

Cambié el nombre de los scripts para que me quedaran con la numeración adecuada considerando el orden en que deben irse ejecutando de acuerdo con lo que indica el README. 

Mi duda es ¿Está bien si borro los  scripts  con los nombre viejos para que esté mejor ordenado el proyecto?  Preferí preguntarte para saber si es mejor conservar todos los scripts para poder tener un mejor Historial de las actualizaciones que se han venido haciendo (Aunque se vean demasiados scripts) o si es mejor dejar únicamente los scripts ya con los nombres actualizados y las modificaciones correctas para que corran adecuadamente.

![Captura de Pantalla 2020-05-24 a la(s) 2 32 58](https://user-images.githubusercontent.com/36178935/82748484-d17c5480-9d67-11ea-9aa2-ecd82a9500bd.png)

Me podrías sugerir qué es lo más adecuado por fa

**Comment by AliciaMstt** [comment]
Lo mejor es borrar los viejos y hacerlo en un commit, ya que esta es la forma de guardar el historial ;)
