### ISSUE TITLE
Comparing numbers of OTU from different read lenght

### ISSUE THREAD

**Issue by camillethuyentruong** [OliviaRN/Tepoztlan_ITS#11]
Generate OTU table in amptk using -min_lenght of 150 or 200
How many OTUs do we get in general, in the negative control and in the positive control

**Comment by OliviaRN** [comment]
Attached is the Table named "MOTUS GET GENERAL". It has the general MOTUs get using a   -min_lenght of 150 and 200.



[MOTUS_GET_GENERAL.xlsx](https://github.com/OliviaRN/Tepoztlan_ITS/files/4788782/MOTUS_GET_GENERAL.xlsx)

**Comment by OliviaRN** [comment]
We decided to use the  -minlenght  200 for the raw sequences. Further, we will use the same -minlenght of 200 for the filtered sequences using the SLIDINGWINDOW 7:20 for R1 and 7:30  for R2 and then we will compare what we get between Raw and Filtered sequences after running the AMPtk  and the rest of the data analysis.
