### ISSUE TITLE
Msj de error (Unable to access jarfile trimmomatic) para Trimmomatic 

### ISSUE THREAD

**Issue by OliviaRN** [OliviaRN/Tepoztlan_ITS#3]
Hola Alicia,

Hice mi carpeta llamada trimfilter aquí:

~/Tepoztlan_ITS/bin$ mkdir -p ../data/trimfilter

para poder guardar ahí mis outputs una vez que corriera los comando de trimmomatic, sin embargo, después de que corrí estos comandos con una de mis secuencias:
´´´
java -jar trimmomatic-0.39/trimmomatic-0.39.jar SE ../data/tepoz/SCC1J_S3_L001_R1_001.fastq.gz ../data/trimfilter/SCC1J_S3_L001_R1_001_trimmed.fastq.gz ILLUMINACLIP:trimmomatic-0.39/adapters/TruSeq3-SE.fa:2:30:10 SLIDINGWINDOW:7:20

´´´

Me aparece el msj de Error :
´´´
Error: Unable to access jarfile trimmomatic-0.39/trimmomatic-0.39.jar
´´´
No sé si sea un problema de permisos  o si estoy haciendo algo mal en la terminal. Ya corrí el comando de java desde bin, como lo hicimos ayer y no tuve problemas, pero al momento de hacer lo de trimmomatic no me funciona ¿Me podrías ayudar por favor? 

Adjunto screenshot de lo que me sale:

![Captura de Pantalla 2020-04-22 a la(s) 12 59 51](https://user-images.githubusercontent.com/36178935/80016779-373f9d00-8499-11ea-9626-8f79ab867cdd.png)

**Comment by AliciaMstt** [comment]
Tienes un error en tu línea de código:

Dice:

`java -jar trimmomatic-0.39/trimmomatic-0.39.jar`

Debe decir:

`java -jar trimmomatic-0.39.jar`

Es decir, el directorio `bin/trimmomatic-0.39` no existe, tienes el archivo `trimmomatic-0.39.jar` directamente sentado en bin.

**Comment by OliviaRN** [comment]
Ya lo corregí y si corrió Alicia. GRACIAS!!!
